Added documentation for button close
unicoderns/ui pull request #29
Opened 2021-12-27 20:28 UTC by alejandronavarroGL

2021-12-27 21:06 UTC, jimmymadrigal requested changes

2021-12-27 21:06 UTC, jimmymadrigal commented on packages/button-close/src/docs/ButtonClose.doc.mdx
> +<ui-button-close :="args" :invert="invert" @close="close" />
extend args as `:disabled="false" :invert="false"`

2021-12-27 21:14 UTC, alejandronavarroGL commented on packages/button-close/src/docs/ButtonClose.doc.mdx
> +<ui-button-close :="args" :invert="invert" @close="close" />
Done

2021-12-27 21:25 UTC, jimmymadrigal approved these changes

2021-12-28 14:08 UTC, jeanpaniagua approved these changes

2021-12-28 14:09 UTC, merged